apiVersion: apps/v1
kind: Deployment
metadata:
  name: "pacman-demo"
spec:
  selector:
    matchLabels:
      name: pacman-demo
  template:
    metadata:
      labels:
        name: pacman-demo
        appname: pacman
    spec:
      containers:
      - image: docker.io/akabarukhin/pacman-demo:{{ required "A valid imageTag is required" .Values.imageTag }}
        imagePullPolicy: Always
        name: pacman-demo
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
      restartPolicy: Always
      securityContext: {}
