apiVersion: apps/v1
kind: Deployment
metadata:
  name: "pacman-demo"
spec:
  selector:
    matchLabels:
      deployment: pacman-demo
  template:
    metadata:
      labels:
        deployment: pacman-demo
    spec:
      containers:
      - image: docker.io/akabarukhin/pacman-demo:{{ .Values.appBranch }}
        imagePullPolicy: IfNotPresent
        name: pacman-demo
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
      restartPolicy: Always
      securityContext: {}
